name: Docker Action
on:
  push:
    branches:
      - develop
    tags:
jobs:
  docker:
    uses: e-CODEX/workflows/.github/workflows/docker-build-push.yaml@main
    with:
      image-name: connector-client
