on:
  push:
    branches:
      - main
jobs:
  check-version:
    name: Check the current release version
    uses: e-CODEX/workflows/.github/workflows/maven-validate-release-version.yaml@main
  tag-version:
    name: Tag the current release version
    needs: check-version
    uses: e-CODEX/workflows/.github/workflows/maven-tag-release-version.yaml@main
  publish-version:
    name: Publish the current release version
    uses: e-CODEX/workflows/.github/workflows/maven-publish-release.yaml@main
    needs: tag-version
    with:
      java-version: 21
      maven-repo-id: 'releases'
      maven-parameters: '-P production,javadoc'
      tag: ${{ needs.tag-version.outputs.tag }}
  publish-docker:
    uses: e-CODEX/workflows/.github/workflows/docker-build-push.yaml@main
    needs: tag-version
    with:
      image-name: connector-client
      tag: ${{ needs.tag-version.outputs.tag }}
